package com.stratum.uiserver.graphics.theme;

public enum ThemeItem {
    BUTTON, BUTTON_PRESSED, BUTTON_HIGHLIGHTED, BUTTON_DISABLED,
    CHECKBOX, CHECKBOX_CHECKED,
    SLIDER_HORIZONTAL, SLIDER_HORIZONTAL_FILL,
    SLIDER_VERTICAL, SLIDER_VERTICAL_FILL,
    PROGRESS_FILL
}
